--TASK01--
CREATE TABLE MY_EMPLOYEE (
    ID         NUMBER(4)    NOT NULL,
    LAST_NAME  VARCHAR2(25),
    FIRST_NAME VARCHAR2(25),
    USERID     VARCHAR2(8),
    SALARY     NUMBER(9,2),
    CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY (ID)
);
--TASK 02--

INSERT INTO MY_EMPLOYEE
VALUES (1, 'Patel', 'Ralph', 'rpatel', 895);

--TASK 03--
INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);

--TASK 03--
INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);

--TASK 04--
SELECT * 
FROM MY_EMPLOYEE;

--TASK 05--
INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (
    &ID,
    '&LAST_NAME',
    '&FIRST_NAME',
    UPPER(SUBSTR('&FIRST_NAME', 1, 1) || SUBSTR('&LAST_NAME', 1, 7)),
    &SALARY
);

--TASK 06--
UPDATE MY_EMPLOYEE
SET LAST_NAME = 'Drexler'
WHERE ID = 3;

--TASK 07--
UPDATE MY_EMPLOYEE
SET SALARY = 1000
WHERE SALARY < 900;

--TASK 08--
DELETE FROM MY_EMPLOYEE
WHERE FIRST_NAME = 'Betty' AND LAST_NAME = 'Dancs';

--TASK 09--
TRUNCATE TABLE MY_EMPLOYEE;


