----1----
CREATE TABLE TRG_DEPT (
    ID INT NOT NULL PRIMARY KEY,
    NAME NVARCHAR(25) NOT NULL
);
GO
SELECT * FROM TRG_DEPT;

----2----
CREATE TABLE DEPARTMENTS (
    DepartmentID INT PRIMARY KEY IDENTITY(1,1),
    DepartmentName NVARCHAR(50) NOT NULL,
    Location NVARCHAR(100),
    ManagerID INT
);
GO
SELECT * FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS (DepartmentName, Location, ManagerID)
VALUES
    ('HR', 'New York', 101),
    ('IT', 'San Francisco', 102),
    ('Finance', 'Chicago', 103),
    ('Marketing', 'Los Angeles', 104),
    ('Operations', 'Houston', 105);
GO
CREATE TABLE DEPT101 (
    ID INT PRIMARY KEY,
    NAME NVARCHAR(25) NOT NULL
);
GO
INSERT INTO DEPT101 (ID, NAME)
SELECT DepartmentID, DepartmentName
FROM DEPARTMENTS;

----3----
CREATE TABLE TRG_EMP (
    ID INT NOT NULL PRIMARY KEY,
    LAST_NAME NVARCHAR(25) NOT NULL,
    FIRST_NAME NVARCHAR(25) NOT NULL,
    DEPT_ID INT NOT NULL
);
GO
ALTER TABLE TRG_EMP
ADD CONSTRAINT FK_DEPT
FOREIGN KEY (DEPT_ID) REFERENCES TRG_DEPT(ID);
GO
SELECT * FROM TRG_EMP;

----4----
ALTER TABLE TRG_EMP
ALTER COLUMN LAST_NAME NVARCHAR(50) NOT NULL;
GO

EXEC sp_columns TRG_EMP;
GO

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRG_EMP' AND COLUMN_NAME = 'LAST_NAME';

----5----
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY IDENTITY(1,1),
    FIRST_NAME NVARCHAR(25) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER NVARCHAR(15),
    HIRE_DATE DATE NOT NULL,
    JOB_ID NVARCHAR(10) NOT NULL,
    SALARY DECIMAL(10, 2) CHECK (SALARY >= 0),
    MANAGER_ID INT,
    DEPARTMENT_ID INT
);
GO

CREATE TABLE TRG_EMPLOYEES (
    ID INT NOT NULL PRIMARY KEY,
    FIRST_NAME NVARCHAR(25) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    DEPT_ID INT NOT NULL
);
GO

INSERT INTO TRG_EMPLOYEES (ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES ;
GO 

----6----
DROP TABLE IF EXISTS TRG_EMP;
GO

SELECT * 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'TRG_EMP';
GO

----7----
EXEC sp_rename 'TRG_EMPLOYEES', 'TRG_EMP';
GO

SELECT * 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'TRG_EMP';
GO

----8----
EXEC sp_columns TRG_EMP;
GO

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRG_EMP';
GO

